[jsx]
jsx = "preact"
jsxImportSource = "preact"
runtime = "automatic"

[build]
jsx = "preact"
jsxFactory = "h"
jsxFragment = "Fragment"

[run]
jsx = "preact"
jsxFactory = "h"
jsxFragment = "Fragment"

[install.scopes]
"react" = "preact/compat"
"react-dom" = "preact/compat"

[serve.static]
plugins = [
  "./src/plugin.ts",
]

[target]
target = "ESNext"
module = "ESNext"
moduleDetection = "force"
moduleResolution = "bundler"